#define KANDINSKY_LargeFont_H

/* This file is auto-generated by the rasterizer and chatgpt */

#include "/Users/Ben/Documents/Numworks_Apps/Numworks_Apps_VS/src/kandinsky/include/kandinsky/coordinate.h"

class LargeFont {
public:
  constexpr static KDCoordinate k_glyphWidth = 10;
  constexpr static KDCoordinate k_glyphHeight = 18;
};

