#define KANDINSKY_SmallFont_H

/* This file is auto-generated by the rasterizer and chatgpt */

#include "/Users/Ben/Documents/Numworks_Apps/Numworks_Apps_VS/src/kandinsky/include/kandinsky/coordinate.h"

class SmallFont {
public:
  constexpr static KDCoordinate k_glyphWidth = 7;
  constexpr static KDCoordinate k_glyphHeight = 14;
};

